### ISSUE TITLE
Cannot find c.client project

### ISSUE THREAD

**Issue by duongtx90** [kaazing/amqp-websocket-c#3]
Hi guys, 
I've intended to use this *_c.client *_ library to connect iOS device with RabbitMQ Server over Kaazing Gateway, but I found that this project was closed. 
Can you give me some help? Thank you!

**Comment by dpwspoon** [comment]
Here it is: https://github.com/kaazing/c.client/tree/develop/amqp

**Comment by dpwspoon** [comment]
We are in general trying to consolidate our client technologies by platform.  Sorry for the confusion, but we hope it will be more discoverable in the future as we reduce the number of repositories we have
